-- AlterTable
ALTER TABLE "Dog" ALTER COLUMN "uuid" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Kennel" ALTER COLUMN "uuid" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Shelter" ALTER COLUMN "uuid" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "uuid" SET DATA TYPE TEXT;
